### ISSUE TITLE
complete RDF Data Modeling Section

### ISSUE THREAD

**Issue by juweeks** [aws-samples/aws-dbs-refarch-graph#2]
[RDF Data Modeling Section](https://github.com/aws-samples/aws-dbs-refarch-graph/tree/master/src/graph-data-modelling#rdf-data-modelling) appears to be incomplete and stuck in a TBD state for the last year now.

**Comment by jtdiscovery** [comment]
👍 on this. I'm exploring a use-case for the RDF+SPARQL and could really use this to show my team.
Is there an ETA?

**Comment by jtdiscovery** [comment]
^ @iansrobinson @hyandell @IanMeyers

**Comment by beebs-systap** [comment]
@jtdiscovery Please reach out to beebs _at_ amazon dot com and we can help.

**Comment by charlesivie** [comment]
see https://github.com/aws-samples/aws-dbs-refarch-graph/tree/rdf-modelling-1/src/graph-data-modelling#rdf-data-modelling
